#uspecify feeds and wing of feed
feeds=[{'feed':'National Review',
	'rss':'http://www.nationalreview.com/articles/feed',
	'link':'http://www.nationalreview.com',
	'wing':'right'},
{'feed':'Politico',
          'rss':'feed://www.politico.com/rss/politicopicks.xml',
        'wing':'left',
        'link':'http://www.politico.com'},
{'feed':'Real Clear Politics',
          'rss':'feed://feeds.feedburner.com/realclearpolitics/qlMj',
        'wing':'right',
        'link':'http://www.realclearpolitics.com'},
{'feed':'Real Clear Politics Commentary',
          'rss':'feed://feeds.feedburner.com/Realclearpolitics-Articles',
        'wing':'right',
        'link':'http://www.realclearpolitics.com'},
{'feed':'Real Clear Politics',
          'rss':'feed://www.realclearpolitics.com/video/index.xml',
        'wing':'right',
        'link':'http://www.realclearpolitics.com'},
{'feed':'Legal Insurrection',
          'rss':'http://feeds.feedburner.com/LegalInsurrection',
        'wing':'right',
        'link':'http://www.legalinsurrection.com'},
{'feed':'American Thinker',
          'rss':'feed://www.americanthinker.com/blog/atom.xml',
        'wing':'right',
        'link':'http://www.americanthinker.com'},
{'feed':'The Gateway Pundit',
          'rss':'feed://www.thegatewaypundit.com/feed/',
        'wing':'right',
        'link':'http://www.thegatewaypundit.com'},
{'feed':'Michelle Malkin',
          'rss':'http://feeds.feedburner.com/michellemalkin/posts',
        'wing':'right',
        'link':'http://michellemalkin.com'},
{'feed':'Hot Air',
          'rss':'feed://feeds.feedburner.com/hotair/main',
        'wing':'right',
        'link':'http://www.hotair.com'},
{'feed':'Right Wing News',
          'rss':'feed://rightwingnews.com/feed/',
        'wing':'right',
        'link':'http://rightwingnews.com'},
{'feed':'Fox News Politics',
          'rss':'feed://feeds.foxnews.com/foxnews/politics',
        'wing':'right',
        'link':'http://www.foxnews.com'},
{'feed':'WorldNetDaily Commentary',
          'rss':'feed://www.wnd.com/index.php?fa=PAGE.rss&title=Commentary',
        'wing':'right',
        'link':'http://www.wnd.com'},
{'feed':'WorldNetDaily',
          'rss':'feed://www.wnd.com/?ol=0&fa=PAGE.rss',
        'wing':'right',
        'link':'http://www.wnd.com'},
{'feed':'American Spectator',
	'rss':'http://feedproxy.google.com/amspecarticles',
	'wing':'right',
	'link':'http://spectator.org'},
{'feed':'Wall Street Journal',
	'rss':'http://online.wsj.com/xml/rss/3_7041.xml',
	'wing':'right',
	'link':'http://www.wsj.com'},
{'feed':'The Weekly Standard',
	'rss':'http://www.weeklystandard.com/rss/site.xml',
	'wing':'right',
	'link':'http://www.weeklystandard.com'},
{'feed':'Media Research Center: Brent Bozell',
	 'rss':'feed://www.mrc.org/rss/bozellcolumn.xml',
	'wing':'right',
	'author':'Brent Bozell',
	'link':'http://www.mrc.org'},
{'feed':'New York Times: David Brooks',
	'rss':'feed://topics.nytimes.com/top/opinion/editorialsandoped/oped/columnists/davidbrooks/index.html?rss=1',
	'wing':'right',
	'link':'http://topics.nytimes.com/top/opinion/editorialsandoped/oped/columnists/davidbrooks/index.html',
	'author':'David Brooks'},
{'feed':'Human Events',
	'rss':'feed://www.humanevents.com/rss/thefrontpage.xml',
	'wing':'right',
	'link':'http://www.humanevents.com'},
{'feed':'New York Times: Paul Krugman Blog',
	'rss':'feed://krugman.blogs.nytimes.com/feed/',
	'wing':'left',
	'link':'http://krugman.blogs.nytimes.com',
	'author':'Paul Krugman'},
{'feed':'National Review: Larry Kudlow',
	'rss':'feed://www.nationalreview.com/kudlows-money-politics/feed',
	'wing':'right',
	'link':'http://www.nationalreview.com/kudlows-money-politics',
	'author':'Larry Kudlow'},
{'feed':'Townhall.com: Thomas Sowell',
	'rss':'feed://townhall.com/xml/columnists/author/thomassowell',
	'wing':'right',
	'link':'http://townhall.com/columnists/thomassowell/',
	'author':'Thomas Sowell'},
{'feed':'SteynOnline: Mark Steyn',
	'rss':'feed://www.steynonline.com/rss.xml',
	'wing':'right',
	'link':'http://www.steynonline.com',
	'author':'Mark Steyn'},
{'feed':'Atlantic Monthly: Andrew Sullivan',
	'rss':'http://feeds.feedburner.com/andrewsullivan/rApM',
	'wing':'left',
	'link':'http://www.theatlantic.com',
	'author':'Andrew Sullivan'},
{'feed':'Washington Post: Left Leaning Opinions',
	'rss':'feed://feeds.washingtonpost.com/rss/opinions/left-leaning',
	'wing':'left',
	'link':'http://www.washingtonpost.com'},
{'feed':'Washington Post: Right Leaning Opinions',
	'rss':'feed://feeds.washingtonpost.com/rss/opinions/right-leaning',
	'wing':'right',
	'link':'http://www.washingtonpost.com'},
{'feed':'Washington Post: Politics',
	'rss':'feed://feeds.washingtonpost.com/rss/politics',
	'wing':'left',
	'link':'http://www.washingtonpost.com'},
{'feed':'L.A. Times: Opinion',
	'rss':'feed://www.latimes.com//news/opinion/rss2.0.xml',
	'wing':'right',
	'link':'http://www.latimes.com'},
{'feed':'CNS News',
	'rss':'feed://cnsnews.com/feeds/all',
	'wing':'right',
	'link':'http://cnsnews.com'},
{'feed':'New York Times: Editorials',
	'rss':'feed://topics.nytimes.com/top/opinion/editorialsandoped/editorials/index.html?rss=1',
	'wing':'left',
	'link':'http://www.nytimes.com'},
{'feed':'Huffington Post: Politics',
	'rss':'feed://www.huffingtonpost.com/feeds/verticals/politics/index.xml',
	'wing':'left',
	'link':'http://www.huffingtonpost.com'}
	]

